In [5]:
# read in clean data first
import pandas as pd
data = pd.read_csv('clean_data.csv')

/Users/huilin/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
data

Unnamed: 0  RA_Report # RA_CAERS Created Date    Year Start_Date  \
0               0      65325.0                1/1/04  2004.0     8/4/03   
1               1      65333.0                1/1/04  2004.0        NaN   
2               2      65335.0                1/1/04  2004.0   11/24/03   
3               3      65336.0                1/1/04  2004.0        NaN   
4               4      65345.0                1/1/04  2004.0   12/21/03   
5               5      65350.0                1/1/04  2004.0        NaN   
6               6      65353.0                1/2/04  2004.0    12/1/03   
7               7      65353.0                1/2/04  2004.0    12/1/03   
8               8      65354.0                1/2/04  2004.0        NaN   
9               9      65355.0                1/2/04  2004.0   10/27/03   
10             10      65356.0                1/2/04  2004.0   10/27/03   
11             11      65357.0                1/2/04  2004.0   10/27/03   
12             12      65379.0                1/3/04  2004.0    11/5/03   
13             13      65387.0                1/3/04  2004.0        NaN   
14             14      65388.0                1/3/04  2004.0   12/30/03   
15             15      65399.0                1/5/04  2004.0   11/22/03   
16             16      65400.0                1/5/04  2004.0     9/5/01   
17             17      65403.0                1/5/04  2004.0     3/4/03   
18             18      65404.0                1/5/04  2004.0        NaN   
19             19      65416.0                1/6/04  2004.0   11/15/03   
20             20      65419.0                1/6/04  2004.0        NaN   
21             21      65420.0                1/6/04  2004.0    11/1/03   
22             22      65420.0                1/6/04  2004.0    11/1/03   
23             23      65420.0                1/6/04  2004.0    11/1/03   
24             24      65420.0                1/6/04  2004.0    11/1/03   
25             25      65420.0                1/6/04  2004.0    11/1/03   
26             26      65420.0                1/6/04  2004.0    11/1/03   
27             27      65420.0                1/6/04  2004.0    11/1/03   
28             28      65420.0                1/6/04  2004.0    11/1/03   
29             29      65420.0                1/6/04  2004.0    11/1/03   
...           ...          ...                   ...     ...        ...   
80139       80139     205260.0              12/15/16  2016.0   10/23/16   
80140       80140     205300.0              12/16/16  2016.0   10/15/16   
80141       80141     205312.0              12/16/16  2016.0        NaN   
80142       80142     205323.0              12/16/16  2016.0   12/14/16   
80143       80143     205325.0              12/16/16  2016.0    12/8/16   
80144       80144     205351.0              12/19/16  2016.0    12/2/16   
80145       80145     205397.0              12/20/16  2016.0   11/23/16   
80146       80146     205473.0              12/21/16  2016.0   12/13/16   
80147       80147     205481.0              12/21/16  2016.0   12/19/16   
80148       80148     205483.0              12/21/16  2016.0        NaN   
80149       80149     205483.0              12/21/16  2016.0        NaN   
80150       80150     205483.0              12/21/16  2016.0        NaN   
80151       80151     205484.0              12/21/16  2016.0        NaN   
80152       80152     205575.0              12/22/16  2016.0   12/20/16   
80153       80153     205616.0              12/23/16  2016.0   12/22/16   
80154       80154     205668.0              12/27/16  2016.0    6/14/16   
80155       80155     205669.0              12/27/16  2016.0        NaN   
80156       80156     205670.0              12/27/16  2016.0        NaN   
80157       80157     205670.0              12/27/16  2016.0        NaN   
80158       80158     205671.0              12/27/16  2016.0        NaN   
80159       80159     205673.0              12/27/16  2016.0    10/7/16   
80160       80160     205680.0  

In [20]:
# import numpy as np
# data['Report_year'] = np.nan
# data['Report_year'] = '20' + data['RA_CAERS Created Date'].str[-2:]

In [7]:
# create new variable: life_threatening
import numpy as np
year_data = data[data['Age Unit'] == 'Year']

#len(year_data)
        #"LIFE THREATENING len(data.index)

47309

In [8]:
data = year_data.sample(n=10000, random_state = 1)

len(data)

10000

In [9]:
data.index = pd.Series(range(10000))
#data.index

In [ ]:
# data['life_threatening'] = np.zeros(len(year_data))

# for i in range(len(year_data)):
#     if data['AEC_One Row Outcomes'].str.contains('DEATH')[i]:
#         data['life_threatening'][i] = 1



In [10]:
data['life_threatening'] = np.zeros(len(data.index))

for i in range(len(data.index)):
    if data['AEC_One Row Outcomes'].str.contains('DEATH')[i]:
        data['life_threatening'][i] = 1


/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [11]:
for i in range(len(data.index)):
    if data['AEC_One Row Outcomes'].str.contains('LIFE THREATENING')[i]:
        data['life_threatening'][i] = 1
        

/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [12]:
data['life_threatening'].value_counts()

0.0    9064
1.0     936
Name: life_threatening, dtype: int64

In [13]:
data.to_csv('life_threatening.csv')

In [14]:
data = pd.read_csv('life_threatening.csv')

In [ ]:
# Start analysis: life_threatening

In [15]:
X = data[['Industry', 'Age','Gender']]  # Age_interval
y = data['life_threatening']

In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(X['Gender'])
X['Gender'] = le.transform(X['Gender']) 

le.fit(X['Industry'])
X['Industry'] = le.transform(X['Industry'])



/Users/huilin/anaconda/lib/python2.7/site-packages/numpy/lib/arraysetops.py:200: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))
/Users/huilin/anaconda/lib/python2.7/site-packages/numpy/lib/arraysetops.py:259: FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  return aux[:-1][aux[1:] == aux[:-1]]
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packa

In [163]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(X)
# enc.fit(X['Gender'])
# #enc.transform(X['Gender']).toarray()

# enc.fit(X['Industry'])
# enc.transform(X['Industry']).toarray()
# #enc.transform(X['Gender']).toarray()

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [122]:
# enc.transform(X['Industry']).toarray()

/Users/huilin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [173]:
(enc.transform(X))

<4000x136 sparse matrix of type '<type 'numpy.float64'>'
	with 12000 stored elements in Compressed Sparse Row format>

In [17]:
# stratified sampling train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 1, stratify = y)


In [19]:
list(X)

['Industry', 'Age', 'Gender']

In [20]:
# Decision tree
from sklearn import tree
DT = tree.DecisionTreeClassifier(random_state=100)
DT.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [21]:
DT.feature_importances_

array([ 0.22115763,  0.70179594,  0.07704644])

In [22]:
DT.n_features_

3

In [174]:
from sklearn.model_selection import cross_val_score
scores_DT = cross_val_score(DT, X_train, y_train, cv=10)
scores_DT

array([ 0.89036545,  0.90697674,  0.89368771,  0.9       ,  0.90333333,
        0.90666667,  0.89666667,  0.90301003,  0.90635452,  0.89632107])

In [13]:
predict = DT.predict(X_test)
from sklearn import metrics
precision = metrics.precision_score(y_test, predict)
recall = metrics.recall_score(y_test, predict)
f1 = metrics.f1_score(y_test, predict)
print(precision, recall, f1)

(0.2608695652173913, 0.065217391304347824, 0.10434782608695652)


In [25]:
data['Age_interval'].value_counts()

41-60     3058
61-80     2989
21-40     2035
0-20      1048
81-100     870
Name: Age_interval, dtype: int64

In [27]:
# DT for [20-40] 
#data20 = data[(data['Age'] >= 20) & (data['Age'] <= 40)]
data20 = data[data['Age_interval'] == '21-40']
X20 = data20[['Industry', 'Age','Gender']]  # Age_interval
y20 = data20['life_threatening']

le = preprocessing.LabelEncoder()
le.fit(X20['Gender'])
X20['Gender'] = le.transform(X20['Gender']) 
le.fit(X20['Industry'])
X20['Industry'] = le.transform(X20['Industry'])


/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [28]:
#from sklearn.model_selection import train_test_split
X20_train, X20_test, y20_train, y20_test = train_test_split(X20, y20, test_size=0.25, random_state = 1, stratify = y20)
DT20 = tree.DecisionTreeClassifier(random_state=100)
DT20.fit(X20_train, y20_train)
DT20.feature_importances_

array([ 0.37193102,  0.51653151,  0.11153747])

In [101]:
predict = DT20.predict(X20_test)
from sklearn import metrics
precision = metrics.precision_score(y20_test, predict)
recall = metrics.recall_score(y20_test, predict)
f1 = metrics.f1_score(y20_test, predict)
print(precision, recall, f1)

(0.375, 0.13636363636363635, 0.19999999999999998)


In [29]:
# DT for 40 - 60
#data40 = data[(data['Age'] >= 40) & (data['Age'] <= 60)]
data40 = data[data['Age_interval'] == '41-60']
X40 = data40[['Industry', 'Age','Gender']]  # Age_interval
y40 = data40['life_threatening']

le = preprocessing.LabelEncoder()
le.fit(X40['Gender'])
X40['Gender'] = le.transform(X40['Gender']) 
le.fit(X40['Industry'])
X40['Industry'] = le.transform(X40['Industry'])



/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [30]:
#from sklearn.model_selection import train_test_split
X40_train, X40_test, y40_train, y40_test = train_test_split(X40, y40, test_size=0.25, random_state = 1, stratify = y40)
DT40 = tree.DecisionTreeClassifier(random_state=100)
DT40.fit(X40_train, y40_train)
DT40.feature_importances_

array([ 0.41168173,  0.53094589,  0.05737238])

In [31]:
# DT for 61 - 80
#data40 = data[(data['Age'] >= 40) & (data['Age'] <= 60)]
data60 = data[data['Age_interval'] == '61-80']
X60 = data60[['Industry', 'Age','Gender']]  # Age_interval
y60 = data60['life_threatening']

le = preprocessing.LabelEncoder()
le.fit(X60['Gender'])
X60['Gender'] = le.transform(X60['Gender']) 
le.fit(X60['Industry'])
X60['Industry'] = le.transform(X60['Industry'])




/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [32]:
#from sklearn.model_selection import train_test_split
X60_train, X60_test, y60_train, y60_test = train_test_split(X60, y60, test_size=0.25, random_state = 1, stratify = y60)
DT60 = tree.DecisionTreeClassifier(random_state=100)
DT60.fit(X60_train, y60_train)
DT60.feature_importances_

array([ 0.47018253,  0.50073318,  0.02908429])

In [36]:
data['industry_pie chart'] = ['Others']*len(data)
for i in range(len(data)):
    if data['Industry'][i] == 'Unconventional_food':
        data['industry_pie chart'][i] = 'Unconventional_food'
    elif data['Industry'][i] == 'Fishery':
        data['industry_pie chart'][i] = 'Fishery'
    elif data['Industry'][i] == 'Dietary Conv Food':
        data['industry_pie chart'][i] = 'Dietary Conv Food'
    elif data['Industry'][i] == 'Bakery Prod':
        data['industry_pie chart'][i] = 'Bakery Prod'
    elif data['Industry'][i] == 'Soft Drink':
        data['industry_pie chart'][i] = 'Soft Drink'
    elif data['Industry'][i] == 'Cosmetics':
        data['industry_pie chart'][i] = 'Cosmetics'
        
    

/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/huilin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set

In [37]:
data['industry_pie chart'].value_counts()

Unconventional_food    7155
Others                 1419
Cosmetics               759
Fishery                 202
Dietary Conv Food       167
Bakery Prod             151
Soft Drink              147
Name: industry_pie chart, dtype: int64

In [39]:
data.to_csv('pie_chart.csv')

In [ ]:
# logistic regression

In [33]:
data['life_threatening'][data['Age_interval'] == 'Male'].value_counts()

Series([], Name: life_threatening, dtype: int64)

In [22]:
data['Report_year'].to_csv('year.csv')

In [34]:
data['Industry'][(data['Gender'] == 'Male') & (data['Age Unit'] == 'Year')].value_counts().index.tolist()

['Unconventional_food',
 'Fishery',
 'Nuts',
 'Cosmetics',
 'Soft Drink',
 'Bakery Prod',
 'Dietary Conv Food',
 'Fruit',
 'Vegetables',
 'Milk',
 'Cereal Prep',
 'Snack Food Item',
 'Mult Food Dinner',
 'Choc',
 'Ice Cream Prod',
 'Baby Food Prod',
 'Candy W',
 'Coffee',
 'Spices, Flavors And Salts',
 'Food Additives (Human Use)',
 'Whole Grain',
 'Filled Milk',
 'Egg',
 'Cheese',
 'Meat, Meat Products and Poultry',
 'Food Sweeteners (Nutritive)',
 'Dressing',
 'Macaroni',
 'Soup',
 'Prep Salad Prod',
 'Vegetable Oils',
 'Gelatin',
 'Beverage Bases',
 'Color Additiv Food',
 'Vegetable Protein Prod',
 'Not Available',
 'Miscellaneous Food Related Items',
 'Alcoholic Beverage']

In [5]:
data['Industry'][(data['Gender'] == 'Male') & (data['Age Unit'] == 'Month')].value_counts().index.tolist()

['Baby Food Prod',
 'Unconventional_food',
 'Dietary Conv Food',
 'Cosmetics',
 'Milk',
 'Soft Drink',
 'Fruit',
 'Nuts',
 'Bakery Prod',
 'Vegetables',
 'Fishery',
 'Cereal Prep',
 'Vegetable Oils',
 'Coffee',
 'Snack Food Item',
 'Mult Food Dinner',
 'Soup',
 'Candy W']

In [5]:
data['Industry'][(data['Gender'] == 'Male') & (data['Age Unit'] == 'Day')].value_counts().index.tolist()

['Baby Food Prod',
 'Unconventional_food',
 'Cosmetics',
 'Soft Drink',
 'Dietary Conv Food',
 'Ice Cream Prod']

In [25]:
data['Industry'][data['Age Unit'] == 'Year'].value_counts()

Unconventional_food                 34011
Cosmetics                            3528
Nuts                                 1207
Fishery                              1012
Bakery Prod                           813
Dietary Conv Food                     737
Soft Drink                            715
Fruit                                 633
Vegetables                            609
Milk                                  583
Cereal Prep                           519
Mult Food Dinner                      311
Snack Food Item                       301
Coffee                                246
Ice Cream Prod                        246
Choc                                  227
Candy W                               218
Food Additives (Human Use)            180
Spices, Flavors And Salts             130
Baby Food Prod                        122
Cheese                                107
Filled Milk                           101
Whole Grain                            90
Food Sweeteners (Nutritive)       

In [27]:
data['Industry'][data['Age Unit'] == 'Month'].value_counts().index.tolist()

['Baby Food Prod',
 'Unconventional_food',
 'Dietary Conv Food',
 'Cosmetics',
 'Soft Drink',
 'Milk',
 'Bakery Prod',
 'Fruit',
 'Vegetables',
 'Nuts',
 'Candy W',
 'Mult Food Dinner',
 'Coffee',
 'Cereal Prep',
 'Beverage Bases',
 'Fishery',
 'Snack Food Item',
 'Soup',
 'Food Additives (Human Use)',
 'Alcoholic Beverage',
 'Vegetable Oils',
 'Food Sweeteners (Nutritive)',
 'Dressing',
 'Ice Cream Prod',
 'Whole Grain']

In [28]:
data['Industry'][data['Age Unit'] == 'Day'].value_counts()

Baby Food Prod         70
Unconventional_food    29
Cosmetics               6
Soft Drink              4
Dietary Conv Food       4
Vegetables              1
Ice Cream Prod          1
Egg                     1
Name: Industry, dtype: int64

In [9]:
#data['Age_interval'][(data['Gender'] == 'Male') & (data['Age Unit'] == 'Day')].value_counts()