In [7]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_predict)

(array([ 1. ,  0.5,  0. ]),
 array([ 1.,  1.,  0.]),
 array([ 1.        ,  0.66666667,  0.        ]),
 array([1, 1, 1]))

In [6]:
import numpy as np
y_test = np.array([[0, 1, 0],[1, 0, 1]])
       
y_predict = np.array([[0, 1, 0],[1, 1, 0]])
       

In [14]:
import numpy as np
X = np.random.randint(5, size=(2, 6))
y = np.array([1, 2, 3, 4, 5, 6])

In [15]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y = lb.fit_transform(y)


In [19]:
for i, item in enumerate(y):
    y[i] = tuple(item)

In [22]:
y

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [13]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)

ValueError: bad input shape (6, 6)