In [6]:
import matplotlib.pyplot as plt
import numpy as np
from itertools import cycle

from sklearn.naive_bayes import BernoulliNB
from sklearn import datasets
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier

In [151]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [128]:
#y = label_binarize(y, classes=[0, 1, 2])

In [20]:
#y

In [20]:
# y = label_binarize(y, classes=[0, 1, 2])
# n_classes = y.shape[1]

In [162]:
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape
#X = np.c_[X, random_state.randn(n_samples, 200 * n_features)]

In [153]:
X_test

array([[ 4.9       ,  3.1       ,  1.5       , ...,  0.4666787 ,
        -1.90542325, -0.33794381],
       [ 7.2       ,  3.        ,  5.8       , ..., -1.05516782,
         1.1857924 ,  0.22426993],
       [ 5.1       ,  3.7       ,  1.5       , ..., -0.79051455,
        -1.75241097,  0.36639879],
       ..., 
       [ 6.8       ,  2.8       ,  4.8       , ..., -0.57860383,
        -0.48089222,  0.67954333],
       [ 5.        ,  3.4       ,  1.6       , ..., -0.57858615,
        -0.45437795, -0.64403991],
       [ 6.        ,  3.4       ,  4.5       , ...,  0.7320434 ,
        -1.35136905,  0.78970575]])

In [183]:
# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5, random_state=1)

# Run classifier
#from sklearn.naive_bayes import MultinomialNB
classifier = OneVsRestClassifier(BernoulliNB())
#classifier = MultinomialNB()
#y_score = classifier.fit(X_train, y_train).predict_proba(X_test)
y_predict = classifier.fit(X_train, y_train).predict(X_test)
#y_score = classifier.fit(X_train, y_train).decision_function(X_test)


In [176]:
# multi NB directly
#y_predict = classifier.fit(X_train, y_train).predict(X_test)
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_predict)
                                #average='macro')

(array([ 1.        ,  0.55813953,  1.        ]),
 array([ 1.       ,  1.       ,  0.2962963]),
 array([ 1.        ,  0.71641791,  0.45714286]),
 array([24, 24, 27]))

In [125]:
# no binary encoding
#y_score[:5]
y_predict

array([1, 0, 2, 0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0,
       1, 1, 0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2,
       2, 0, 0, 2, 0, 2])

In [126]:
y_test

array([1, 0, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 2, 2,
       2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 2, 1, 2, 2, 1, 2, 1, 0, 0,
       0, 1, 0, 2, 1, 0, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 0, 1, 1, 2, 0, 0,
       2, 0, 2, 1, 2, 0])

In [184]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_predict)
                                #average='macro')

(array([ 0.  ,  0.32,  0.  ]),
 array([ 0.,  1.,  0.]),
 array([ 0.        ,  0.48484848,  0.        ]),
 array([24, 24, 27]))

##### 

In [139]:
y_score[0][0]

0.0

In [140]:
# with encoding
from sklearn import metrics
precision = metrics.precision_score(y_test, y_score, average = 'micro')
recall = metrics.recall_score(y_test, y_score, average = 'micro')
f1 = metrics.f1_score(y_test, y_score, average = 'micro')
print(precision, recall, f1)

(0.0, 0.0, 0.0)


In [107]:
# binary encoding
#y_predict
precision = dict()
recall = dict()
for i in range(3):
    precision[i], recall[i], _ = precision_recall_curve(y_test[:, i],
                                                        y_predict[:, i])


In [118]:
from sklearn import metrics
precision = metrics.precision_score(y_test, y_predict, average = 'micro')
recall = metrics.recall_score(y_test, y_predict, average = 'micro')
f1 = metrics.f1_score(y_test, y_predict, average = 'micro')
print(precision, recall, f1)

(0.0, 0.0, 0.0)


In [114]:
y_predict[:,2]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [108]:
precision[0]

array([ 0.23333333,  1.        ])

In [109]:
precision[1]

array([ 0.36666667,  1.        ])

In [110]:
precision[2]

array([ 0.4,  1. ])

In [121]:
y_predict

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0,

In [101]:
y_test

array([[0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]])

In [95]:
y_score

array([[  3.63997035e-317,   0.00000000e+000,   0.00000000e+000],
       [  9.72311310e-319,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  6.28155062e-320,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.09692427e-304,   0.00000000e+000,   0.00000000e+000],
       [  9.88174762e-284,   0.00000000e+000,   0.00000000e+000],
       [  3.92429161e-303,   0.00000000e+000,   0.00000000e+000],
       [  4.69579944e-308,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  4.63398991e-319,   0.00000000e+000,   0.00000000e+000],
       [  4.07060686e-319,   0.00000000e+000,   0.00000000e+000],
       [  6.15310834e-262,   0.00000000e+000,   0.00000000e+000],
       [  

In [78]:
y_test

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [66]:
precision

{0: array([ 0.3,  1. ]), 1: array([ 0.3,  1. ]), 2: array([ 0.4,  1. ])}

In [67]:
y_predict

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])