In [41]:
import matplotlib.pyplot as plt
import numpy as np
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.multiclass import OneVsRestClassifier

In [44]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Binarize the output
lb = LabelBinarizer()
y = lb.fit_transform(y)
#n_classes = y.shape[1]

# Add noisy features
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape
#X = np.c_[X, random_state.randn(n_samples, 200 * n_features)]

# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3,
                                                    random_state=random_state)

#from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
# Run classifier
#classifier = OneVsRestClassifier(MultinomialNB())
classifier = svm.SVC(kernel='linear', probability=True)
#y_score = classifier.fit(X_train, y_train).predict_prob(X_test)
clf = classifier.fit(X_train, y_train).predict(X_test)


ValueError: bad input shape (105, 3)

In [45]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [1]:
# precision = dict()
# recall = dict()
# average_precision = dict()
# for i in range(n_classes):
#     precision[i], recall[i], _ = precision_recall_curve(y_test[:, i],
#                                                         y_score[:, i])

In [54]:
y_predict[:5]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
y_test[:5]

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [5]:
classifier.label_binarizer_ 
classifier.multilabel_

True

In [4]:
# with encoding
from sklearn import metrics
precision = metrics.precision_score(y_test, y_predict, average = 'micro')
recall = metrics.recall_score(y_test, y_predict, average = 'micro')
f1 = metrics.f1_score(y_test, y_predict, average = 'micro')
print(precision, recall, f1)

(0.31578947368421051, 0.13333333333333333, 0.18750000000000003)


In [6]:
# with encoding
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_predict)

(array([ 0.14285714,  0.33333333,  0.44444444]),
 array([ 0.07142857,  0.05555556,  0.30769231]),
 array([ 0.0952381 ,  0.0952381 ,  0.36363636]),
 array([14, 18, 13]))

In [17]:
# no encoding
from sklearn import metrics
precision = metrics.precision_score(y_test, y_predict, average = 'macro')
recall = metrics.recall_score(y_test, y_predict, average = 'macro')
f1 = metrics.f1_score(y_test, y_predict, average = 'macro')
print(precision, recall, f1)

(0.48148148148148145, 0.66666666666666663, 0.53846153846153844)


/opt/conda/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/opt/conda/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [18]:
# no encoding
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_predict)
                                #average='macro')

(array([ 1.        ,  0.        ,  0.44444444]),
 array([ 1.,  0.,  1.]),
 array([ 1.        ,  0.        ,  0.61538462]),
 array([21, 30, 24]))

In [6]:
precision[0]

array([ 0.42592593,  0.41509434,  0.42307692,  0.43137255,  0.44      ,
        0.44897959,  0.45833333,  0.46808511,  0.47826087,  0.48888889,
        0.5       ,  0.51162791,  0.5       ,  0.51219512,  0.525     ,
        0.53846154,  0.55263158,  0.54054054,  0.55555556,  0.57142857,
        0.58823529,  0.57575758,  0.59375   ,  0.61290323,  0.63333333,
        0.65517241,  0.64285714,  0.62962963,  0.61538462,  0.64      ,
        0.625     ,  0.65217391,  0.68181818,  0.66666667,  0.65      ,
        0.63157895,  0.66666667,  0.70588235,  0.75      ,  0.8       ,
        0.85714286,  0.84615385,  0.83333333,  0.90909091,  0.9       ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [14]:
len(y_test[:,0])

75

In [12]:
#y_test

In [13]:
len(y_score[:, 0])

75